split_left_right = "ctrl+shift+o"
split_top_bottom = "ctrl+shift+e"
resize_left      = "ctrl+shift+left"
resize_right     = "ctrl+shift+right"
resize_up        = "ctrl+shift+up"
resize_down      = "ctrl+shift+down"
focus_left       = "alt+left"
focus_right      = "alt+right"
focus_up         = "alt+up"
focus_down       = "alt+down"
new_tab_end      = "ctrl+shift+t"
new_tab_after    = "ctrl+shift+r"
close_pane       = "ctrl+shift+w"
close_tab        = "ctrl+shift+q"
copy             = ["ctrl+shift+c", "ctrl+insert"]
paste            = ["ctrl+shift+v", "shift+insert"]
font_inc         = "ctrl+kp_add"
font_dec         = "ctrl+kp_subtract"
font_reset       = "ctrl+kp_multiply"
open_config      = "ctrl+comma"
tab_1            = "alt+1"
tab_2            = "alt+2"
tab_3            = "alt+3"
tab_4            = "alt+4"
tab_5            = "alt+5"
tab_6            = "alt+6"
tab_7            = "alt+7"
tab_8            = "alt+8"
tab_9            = "alt+9"
