name: Check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libgtk-4-dev \
            libvte-2.91-gtk4-dev \
            libgirepository1.0-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.13.1
          args: --allow-parallel-runners --timeout 5m

      - name: go vet
        run: go vet ./...

      - name: go test
        run: go test -count=1 ./...

      - name: Install osv-scanner
        run: go install github.com/google/osv-scanner/cmd/osv-scanner@v1.9.2

      - name: osv-scanner
        run: osv-scanner -r .
